services:
  - type: web
    name: vega-web
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
